<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AmenityBookingService.Domain\AmenityBookingService.Domain.csproj" />
    <ProjectReference Include="..\AmenityBookingService.Application\AmenityBookingService.Application.csproj" />
    <ProjectReference Include="..\..\Shared\SharedLibrary\SharedLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\notification.proto" GrpcServices="Client" />
    <Protobuf
      Include="..\..\IdentityService\IdentityService.API\Protos\identity.proto"
      GrpcServices="Client"
      Link="Protos\identity.proto"
    />
  </ItemGroup>

  <ItemGroup>
    <None Update="Persistence\SeedData\*.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
