// <auto-generated />
using System;
using AmenityBookingService.Infrastructure.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmenityBookingService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618162747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DB_TEAM_C_amenity")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rules");

                    b.Property<Guid>("SlotTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_type_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_amenities");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("i_x_amenities_slot_type_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_amenities_status_id");

                    b.ToTable("amenities", "DB_TEAM_C_amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.AmenityBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmenitySlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenity_slot_id");

                    b.Property<Guid>("BookingStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_status_id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer")
                        .HasColumnName("people_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_amenity_bookings");

                    b.HasIndex("AmenitySlotId")
                        .HasDatabaseName("i_x_amenity_bookings_amenity_slot_id");

                    b.HasIndex("BookingStatusId")
                        .HasDatabaseName("i_x_amenity_bookings_booking_status_id");

                    b.HasIndex("UserId", "AmenitySlotId")
                        .IsUnique()
                        .HasDatabaseName("i_x_amenity_bookings_user_id_amenity_slot_id");

                    b.ToTable("amenity_bookings", "DB_TEAM_C_amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.AmenitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentBookingCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_booking_count");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<DateTime>("SlotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_date");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot_label");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_amenity_slots");

                    b.HasIndex("AmenityId", "SlotDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("i_x_amenity_slots_amenity_id_slot_date_start_time");

                    b.ToTable("amenity_slots", "DB_TEAM_C_amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.RefSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_sets");

                    b.ToTable("ref_sets", "DB_TEAM_C_amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.RefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RefSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_set_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_terms");

                    b.HasIndex("RefSetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_ref_terms_ref_set_id_code");

                    b.ToTable("ref_terms", "DB_TEAM_C_amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("AmenityBookingService.Domain.Entities.RefTerm", "SlotType")
                        .WithMany("Amenities")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_amenities__ref_terms_slot_type_id");

                    b.HasOne("AmenityBookingService.Domain.Entities.RefTerm", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_amenities__ref_terms_status_id");

                    b.Navigation("SlotType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.AmenityBooking", b =>
                {
                    b.HasOne("AmenityBookingService.Domain.Entities.AmenitySlot", "AmenitySlot")
                        .WithMany("AmenityBookings")
                        .HasForeignKey("AmenitySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_amenity_bookings__amenity_slots_amenity_slot_id");

                    b.HasOne("AmenityBookingService.Domain.Entities.RefTerm", "BookingStatus")
                        .WithMany("AmenityBookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_amenity_bookings__ref_terms_booking_status_id");

                    b.Navigation("AmenitySlot");

                    b.Navigation("BookingStatus");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.AmenitySlot", b =>
                {
                    b.HasOne("AmenityBookingService.Domain.Entities.Amenity", "Amenity")
                        .WithMany("AmenitySlots")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_amenity_slots_amenities_amenity_id");

                    b.Navigation("Amenity");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.RefTerm", b =>
                {
                    b.HasOne("AmenityBookingService.Domain.Entities.RefSet", "RefSet")
                        .WithMany("RefTerms")
                        .HasForeignKey("RefSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ref_terms_ref_sets_ref_set_id");

                    b.Navigation("RefSet");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("AmenitySlots");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.AmenitySlot", b =>
                {
                    b.Navigation("AmenityBookings");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.RefSet", b =>
                {
                    b.Navigation("RefTerms");
                });

            modelBuilder.Entity("AmenityBookingService.Domain.Entities.RefTerm", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("AmenityBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
